#!sh syntaxcolor
# this is a comment$
# all the required rules and symbols, along with the bonus ones, will be
# shown here. spacing is not important

#RULE:
#(A + B) ^  (C + D)       <=> !C      		# A and B if and only if not C test
#(((Q | !Z ) ^ (A + B)) ^ !C) + K <=> !C    # A and B if and only if not C test

# !C           => E        # C implies E
# E           => !C       # C implies E
# A + B + C   => D        # A and B and C implies D
# !A | B      => C        # A or B implies C
# A + !B      => F         # A and not B implies F
# C | !G      => H        # C or not G implies H
# V ^ W       => X        # V xor W implies X
# # A + B       => Y + Z    # A and B implies Y and Z
# # C | D       => X | V    # C or D implies X or V
# E + F       => !V       # E and F implies not V
# A + B       <=> C       # A and B if and only if C
# A + B       <=> !C      # A and B if and only if not C
# A + B       <=> !C
# A | B 		=> C
# A + C 		=> C
A + D 		=> C
# A + D 		=> !C
A + B 		=> C
A + B 		=> D
# A + F 		=> !C
# A + F 		=> C
# A + !B 		=> E


# C ^ H       => D        # C implies E
# B + !H      => E        # C implies E
# !idiot 	    => intelligent        # C implies E
# B           => C        # C implies E
# A           => B        # C implies E
# A           <=> B        # C implies E
# A           <=> B        # C implies E
# A + B + C   <=> D        # C implies E
# B | A       <=> D        # C implies E

# HasHair									=> Mammal
# HasClaws + SharpTeeth					=> Carnivore
# EatMeat									=> Carnivore
# Mammal + Carnivore + Spots + VeryFast	=> Cheetah



# =HasHair  HasClaws + SharpTeeth Spots + VeryFast		# Initial facts :  
=AB   	# Initial facts : A, B and G are true. All others are false.  

		# If no facts are initially true, then a simple "=" followed
		# by a newline is used

? A B C	# Queries :
# ?GVX	# Queries : What are G, V and X ?


		# 					X
		# 					|
		# 		A	-	-	+	-	-	B -  -	+	-	-	H
		# 								|
		#						 C	-	+	-	D
