#!/usr/bin/python

from Expert import *
import sys
# print sys.argv

##############################
############ MAIN ############
##############################

e = Expert()

if len(sys.argv) <= 1:
	print "Missing file"
	exit(1)

file = sys.argv[1]

try:
	open(file, 'r')
except IOError:
	print "Can't read: " + file
	exit(1)

e.readFile(file)
e.initialize()
e.checkConflict()
e.checkQueriesExist()
e.checkFactsExist()

e.setInitialFact()

# ret = e.compute(False, "+", True)
# print ret

# ret = e.computeSimpleNaturalRule("D")
# print ret

# e.printAll()
# e.printElement()
e.showQueries()
# e.printElement()


# print "--------------------"
# ret = e.computeQueries('C')
# # print ret
# print "--------------------"
# print "--------------------"
# ret = e.computeQueries('!C')
# print ret
# print "--------------------"
# print qr + " = " + str(ret)

# e.printElement()
