#!/usr/bin/python

from Expert import *
import sys
# print sys.argv

# DEBUG = True;
DEBUG = False;

##############################
############ MAIN ############
##############################

e = Expert()

if len(sys.argv) <= 1:
	print "Missing file"
	exit(1)

file = sys.argv[1]

try:
	open(file, 'r')
except IOError:
	print "Can't read: " + file
	exit(1)

e.readFile(file)
e.initialize()
e.checkConflict()
e.checkQueriesExist()
e.checkFactsExist()

e.setInitialFact()

if DEBUG == True:
	e.printAll()
	e.printElement()

e.showQueries()
