#!/usr/bin/python

from Expert import *

##############################
############ MAIN ############
##############################

e = Expert()

e.readFile('data')
e.initialize()
e.checkConflict()
e.checkQueriesExist()
e.checkFactsExist()

e.setInitialFact()

e.printAll()
e.printElement()
e.showQueries()

